name: create TOC

on: 
  workflow_dispatch:

permissions:
  contents: write

name: TOC Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_PATHS: /README.md
